# yaml-language-server: $schema=https://taskfile.dev/schema.json
# cspell:ignore taskfile,vcpkg,msbuild,makefiles,deinit

version: '3'

# set -eaux
shopt:
  - expand_aliases
  - nullglob

vars:
  BUILD_DIR_NAME: .build
  BUILD_SCRIPT_PATH: .github/build/build.sh
  SHELL: C:/Program Files/Git/bin/bash.exe

tasks:
  default:
    cmds:
      - task: build
      - cmd: cmake -B .build -S .
      - cmd: cmake --build .build

  rebuild:
    cmds:
      - task clean
      - task build

  build:
    cmds:
      - task: build-gcc
      - task: build-curl
      - task: build-openssl
      - task: build-wxwidgets

  clean:
    cmds:
      - cmd: rm -rf "{{joinPath .TASKFILE_DIR .BUILD_DIR_NAME}}"
        ignore_error: true
      - cmd: cmd.exe /d /e:on /c rmdir /s /q "{{joinPath .TASKFILE_DIR .BUILD_DIR_NAME}}"
        ignore_error: true

  copy-resources:
    sources:
      - '{{joinPath .TASKFILE_DIR "FreeFileSync" "Build" "Resources"}}/*'
    generates:
      - '{{joinPath .TASKFILE_DIR .BUILD_DIR_NAME "Resources"}}/*'
    cmds:
      - cmd: |
          (
            echo ".zip\\"
          ) > "{{joinPath .TASKFILE_DIR .BUILD_DIR_NAME "ExcludedResources.lst"}}"
      - cmd: |
          xcopy \
            /Y \
            /EXCLUDE:"{{joinPath .TASKFILE_DIR .BUILD_DIR_NAME "ExcludedResources.lst"}}" \
            /E /I /H /B /R /C \
            "{{joinPath .TASKFILE_DIR "FreeFileSync" "Build" "Resources"}}" \
            "{{joinPath .TASKFILE_DIR .BUILD_DIR_NAME "Resources"}}" \

  zip-icons:
    cmds:
      - task: zip
        vars: { ZIP_RESOURCE_NAME: Icons }

  zip-languages:
    cmds:
      - task: zip
        vars: { ZIP_RESOURCE_NAME: Languages }

  zip:
    internal: true
    requires:
      vars: [BUILD_DIR_NAME, TASKFILE_DIR, ZIP_RESOURCE_NAME]
    sources:
      - '{{joinPath .TASKFILE_DIR "FreeFileSync" .ZIP_RESOURCE_NAME}}/*'
    generates:
      - '{{joinPath .TASKFILE_DIR .BUILD_DIR_NAME "Resources" .ZIP_RESOURCE_NAME}}.zip'
    cmds:
      - cmd: |
          7z a -tzip \
            "{{joinPath .TASKFILE_DIR .BUILD_DIR_NAME "Resources" .ZIP_RESOURCE_NAME}}.zip" \
            "{{joinPath .TASKFILE_DIR "FreeFileSync" .ZIP_RESOURCE_NAME}}"

  format:
    cmds:
      - cmd: pnpm exec prettier --write .

  build-gcc:
    aliases: [gcc]
    sources:
      - .github/build/build-gcc.sh
    generates:
      - .build/gcc-12.1.0/obj/Makefile
    cmds:
      - cmd: |
          "{{ fromSlash .SHELL }}" "{{ joinPath .TASKFILE_DIR ".github/build/build-gcc.sh" | toSlash }}"

  build-curl:
    aliases: [curl]
    sources:
      - .github/build/build-curl.sh
    generates:
      - ./.build/curl-*/**/*
    cmds:
      - cmd: |
          "{{ fromSlash .SHELL }}" "{{ joinPath .TASKFILE_DIR ".github/build/build-curl.sh" | toSlash }}"

  build-openssl:
    aliases: [openssl]
    sources:
      - .github/build/build-openssl.sh
    generates:
      - ./.build/openssl-*/**/*
    cmds:
      - cmd: |
          "{{ fromSlash .SHELL }}" "{{ joinPath .TASKFILE_DIR ".github/build/build-openssl.sh" | toSlash }}"

  build-wxwidgets:
    aliases: [wxwidgets, wx]
    sources:
      - .github/build/build-wxwidgets.sh
    generates:
      - ./.build/wxwidgets-*/**/*
    cmds:
      - cmd: |
          "{{ fromSlash .SHELL }}" "{{ joinPath .TASKFILE_DIR ".github/build/build-wxwidgets.sh" | toSlash }}"
