# https://taskfile.dev

version: '3'

vars:
  BUILD_DIR_NAME: .build

tasks:
  default:
    deps: [build]

  build:
    sources:
      - .github/build/build.sh
    cmds:
      - cmd: sh "{{joinPath .TASKFILE_DIR ".github" "build" "build.sh"}}"
